-- Add new chart types to ChartType enum
ALTER TYPE "ChartType" ADD VALUE IF NOT EXISTS 'DONUT';
ALTER TYPE "ChartType" ADD VALUE IF NOT EXISTS 'SCATTER';
ALTER TYPE "ChartType" ADD VALUE IF NOT EXISTS 'FUNNEL';
ALTER TYPE "ChartType" ADD VALUE IF NOT EXISTS 'WATERFALL';
ALTER TYPE "ChartType" ADD VALUE IF NOT EXISTS 'HEATMAP';
ALTER TYPE "ChartType" ADD VALUE IF NOT EXISTS 'RADAR';
